name: Automated Testing

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'  # Run at 10:00 AM every Monday

jobs:
        
 Jmeter_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get IP Addresses
        id: ip
        uses: candidob/get-runner-ip@v1.0.0
      - name: See IP Addresses
        run: |
                  echo ${{ steps.ip.outputs.ipv4 }}
                  echo ${{ steps.ip.outputs.ipv6 }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Download and Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/
          echo 'export PATH=/opt/apache-jmeter-5.6.3/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
      - name: Run JMeter Tests
        run: /opt/apache-jmeter-5.6.3/bin/jmeter -n -t "JmeterAssignment/CredentialsView Results Tree.jmx" -l "results.jtl" -j "results.log" -e -o "dashboard_reports"


      - name: Upload JMeter Logs
        if: always()  # Ensure reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: JMeter Logs
          path: JmeterAssignment
          overwrite: true




            
         


   
